global:
  scrape_interval: 15s

scrape_configs:
  # Scrape the main app (blue/green deployment - both containers, one will be down)
  - job_name: 'hsduarte-app'
    scheme: http
    metrics_path: /metrics
    honor_labels: true
    static_configs:
      - targets: 
          - 'hsduarte-website-4000:4000'
          - 'hsduarte-website-4001:4000'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
