global:
  scrape_interval: 15s

scrape_configs:
  # Scrape the app on both possible ports (blue/green); one may fail when inactive
  - job_name: 'hsduarte-app'
    scheme: http
    metrics_path: /metrics
    honor_labels: true
    static_configs:
      - targets: ['127.0.0.1:4000']

  # Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['127.0.0.1:9090']
